// Service to load stock data from static JSON file (generated by GitHub Actions)
// This is an alternate version that reads from public/data/stocks.json instead of making API calls
// Use this for production when the JSON file is available

const STATIC_DATA_URL = "/data/stocks.json";

export interface PriceData {
  date: string;
  price: number;
}

interface StaticStockData {
  lastUpdated: string;
  stocks: {
    [key: string]: PriceData[]; // Key format: "SYMBOL_YEAR"
  };
}

// Cache the loaded data to avoid re-fetching
let cachedData: StaticStockData | null = null;
let cacheLoadPromise: Promise<StaticStockData | null> | null = null;

/**
 * Loads the static JSON file (cached after first load)
 * @returns StaticStockData or null if file doesn't exist
 */
const loadStaticData = async (): Promise<StaticStockData | null> => {
  // Return cached data if available
  if (cachedData) {
    return cachedData;
  }

  // If already loading, wait for that promise
  if (cacheLoadPromise) {
    return await cacheLoadPromise;
  }

  // Start loading
  cacheLoadPromise = (async () => {
    try {
      const response = await fetch(STATIC_DATA_URL);
      if (!response.ok) {
        console.warn("Static data file not found, returning null");
        return null;
      }

      const data: StaticStockData = await response.json();
      cachedData = data;
      console.log(
        `Loaded static stock data (last updated: ${data.lastUpdated})`
      );
      return data;
    } catch (error) {
      console.error("Error loading static stock data:", error);
      return null;
    } finally {
      cacheLoadPromise = null; // Clear the loading promise
    }
  })();

  return await cacheLoadPromise;
};

/**
 * Fetches historical stock data from static JSON file
 * @param symbol Stock ticker symbol (e.g., "AAPL")
 * @param year Year to fetch data for (default: 2025)
 * @param retries Not used, kept for interface compatibility
 * @returns Array of price data points with date and price
 */
export const fetchStockData = async (
  symbol: string,
  year: number = 2025,
  retries: number = 3
): Promise<PriceData[]> => {
  const staticData = await loadStaticData();
  if (!staticData) {
    console.warn(`Static data not available for ${symbol} (${year})`);
    return [];
  }

  const key = `${symbol}_${year}`;
  const data = staticData.stocks[key];

  if (!data || data.length === 0) {
    console.warn(`No data found for ${symbol} (${year}) in static file`);
    return [];
  }

  console.log(
    `Loaded ${symbol} (${year}) from static data: ${data.length} data points`
  );
  return data;
};

/**
 * Fetches stock data for multiple symbols from static JSON file
 * @param symbols Array of stock ticker symbols
 * @param delayMs Not used, kept for interface compatibility
 * @returns Map of symbol to price data array
 */
export const fetchMultipleStockData = async (
  symbols: string[],
  delayMs: number = 12000
): Promise<Map<string, PriceData[]>> => {
  const staticData = await loadStaticData();
  if (!staticData) {
    console.warn("Static data not available");
    return new Map();
  }

  const dataMap = new Map<string, PriceData[]>();

  // Try to get data for current year first, then previous year
  const currentYear = new Date().getFullYear();
  const years = [currentYear, currentYear - 1];

  symbols.forEach((symbol) => {
    for (const year of years) {
      const key = `${symbol}_${year}`;
      const data = staticData.stocks[key];
      if (data && data.length > 0) {
        dataMap.set(symbol, data);
        break; // Found data for this symbol, move to next
      }
    }
  });

  return dataMap;
};

/**
 * Fetches stock data progressively from static JSON file
 * Calls onProgress for each stock as it's loaded
 * @param symbols Array of stock ticker symbols
 * @param onProgress Callback called when each stock is loaded (symbol, data, currentIndex, total)
 * @param year Year to fetch data for (default: 2025)
 * @param initialDelayMs Not used, kept for interface compatibility
 * @param rateLimitedDelayMs Not used, kept for interface compatibility
 */
export const fetchMultipleStockDataProgressive = async (
  symbols: string[],
  onProgress: (
    symbol: string,
    data: PriceData[],
    currentIndex: number,
    total: number
  ) => void,
  year: number = 2025,
  initialDelayMs: number = 2000,
  rateLimitedDelayMs: number = 12000
): Promise<void> => {
  const staticData = await loadStaticData();
  if (!staticData) {
    console.warn("Static data not available");
    // Call onProgress with empty data for all symbols
    symbols.forEach((symbol, index) => {
      onProgress(symbol, [], index + 1, symbols.length);
    });
    return;
  }

  let completed = 0;
  symbols.forEach((symbol) => {
    const key = `${symbol}_${year}`;
    const data = staticData.stocks[key] || [];

    if (data.length > 0) {
      completed++;
      console.log(
        `Loaded ${symbol} (${year}) from static data: ${data.length} data points`
      );
    } else {
      console.warn(`No data found for ${symbol} (${year}) in static file`);
    }

    onProgress(symbol, data, completed, symbols.length);
  });
};
